### ISSUE TITLE
Import error resolution workflow / tooling

### ISSUE THREAD

**Issue by jde** [coralproject/sponge#13]
__Challenge__: When importing up to many millions of datapoints into Coral, much can go wrong. Exporting in the wrong order of precidence can lead to foreign keys being missing. Mis-shaped documents or unrecognized characters can lead to dropped documents. 

__Solution__: Identify documents that did not import properly, diagnose why, address the issue(s) and efficiently reimport. Fold all this into a coherent workflow.

**Comment by gabelula** [comment]
About the workflow:

    1. do bulk import (done)
    2. receive report of documents that didn't insert (Logging into elasticsearch)
    3. review any error information that came back from the server  (manual)
    4. quickly access the documents from the source that weren't inserted into the coral db (aka, query them from the source db to see what may have caused the error)  (manual)

    1. perform another import on only the ones that failed
    2. receive a report of the ones that are still failing  (Logging into elasticsearch)

We discussed about tracking information from the import into elasticsearch or mongodb. Do you think this is overkill right now?

**Comment by gabelula** [comment]
if we make a report at the end of the execution

1. do we make them using log package, modifying the package log that we are using

or

2. do we just send everything to stdout without logging(edited)

or 

3. save into a mongodb collection (and use the same for the last record that was imported)

or 

4. look into using ELK


This report :

. is going to be showed at the end
. be used to import failed documents when sponge is rerun with a "reimport" flag

**Comment by gabelula** [comment]
For phase 1, we are going to use a text file for the report. 

CSV errors file with this fields:

table,  id, row, "what went wrong"

We will resolve the report on the last updated document later.
