### ISSUE TITLE
Integrate MongoDB strategies

### ISSUE THREAD

**Issue by jde** [coralproject/sponge#19]
__Challenge__: Source data will come from varying databases.  Most commonly, these appear to be MySQL and MongoDB.  The current coral code only support MySQL.  There is code in Pillar that imports from Mongo.

__Solution__: Dynamicize the db handling in sponge to account for mongodb and mysql.  Document how a third database driver would be added.

**Comment by gabelula** [comment]
Started here: https://github.com/coralproject/sponge/blob/master/pkg/source/mongodb.go

**Comment by gabelula** [comment]
It still needs to document how a third database driver would be added. Issue #40
